use array::ArrayTrait;
use orion::operators::tensor::core::{TensorTrait, Tensor, ExtraParams};
use orion::operators::tensor::implementations::impl_tensor_i32::Tensor_i32;
use orion::numbers::fixed_point::core::FixedImpl;
use orion::numbers::signed_integer::i32::i32;

fn sequential_quant_dense_1_MatMul_sequential_quant_dense_1_LastValueQuant_FakeQuantWithMinMaxVars() -> Tensor<i32> {
    let mut shape = ArrayTrait::<usize>::new();
    shape.append(100);
    let mut data = ArrayTrait::<i32>::new();
    data.append(i32 { mag: 193, sign: false });
    data.append(i32 { mag: 33, sign: false });
    data.append(i32 { mag: 67, sign: false });
    data.append(i32 { mag: 34, sign: false });
    data.append(i32 { mag: 203, sign: false });
    data.append(i32 { mag: 221, sign: false });
    data.append(i32 { mag: 139, sign: false });
    data.append(i32 { mag: 61, sign: false });
    data.append(i32 { mag: 190, sign: false });
    data.append(i32 { mag: 129, sign: false });
    data.append(i32 { mag: 230, sign: false });
    data.append(i32 { mag: 222, sign: false });
    data.append(i32 { mag: 40, sign: false });
    data.append(i32 { mag: 220, sign: false });
    data.append(i32 { mag: 14, sign: false });
    data.append(i32 { mag: 21, sign: false });
    data.append(i32 { mag: 58, sign: false });
    data.append(i32 { mag: 208, sign: false });
    data.append(i32 { mag: 19, sign: false });
    data.append(i32 { mag: 232, sign: false });
    data.append(i32 { mag: 207, sign: false });
    data.append(i32 { mag: 52, sign: false });
    data.append(i32 { mag: 0, sign: false });
    data.append(i32 { mag: 200, sign: false });
    data.append(i32 { mag: 244, sign: false });
    data.append(i32 { mag: 235, sign: false });
    data.append(i32 { mag: 232, sign: false });
    data.append(i32 { mag: 17, sign: false });
    data.append(i32 { mag: 26, sign: false });
    data.append(i32 { mag: 23, sign: false });
    data.append(i32 { mag: 246, sign: false });
    data.append(i32 { mag: 6, sign: false });
    data.append(i32 { mag: 24, sign: false });
    data.append(i32 { mag: 24, sign: false });
    data.append(i32 { mag: 198, sign: false });
    data.append(i32 { mag: 203, sign: false });
    data.append(i32 { mag: 246, sign: false });
    data.append(i32 { mag: 217, sign: false });
    data.append(i32 { mag: 45, sign: false });
    data.append(i32 { mag: 244, sign: false });
    data.append(i32 { mag: 50, sign: false });
    data.append(i32 { mag: 231, sign: false });
    data.append(i32 { mag: 19, sign: false });
    data.append(i32 { mag: 9, sign: false });
    data.append(i32 { mag: 158, sign: false });
    data.append(i32 { mag: 14, sign: false });
    data.append(i32 { mag: 6, sign: false });
    data.append(i32 { mag: 12, sign: false });
    data.append(i32 { mag: 218, sign: false });
    data.append(i32 { mag: 241, sign: false });
    data.append(i32 { mag: 215, sign: false });
    data.append(i32 { mag: 187, sign: false });
    data.append(i32 { mag: 233, sign: false });
    data.append(i32 { mag: 9, sign: false });
    data.append(i32 { mag: 18, sign: false });
    data.append(i32 { mag: 7, sign: false });
    data.append(i32 { mag: 173, sign: false });
    data.append(i32 { mag: 27, sign: false });
    data.append(i32 { mag: 2, sign: false });
    data.append(i32 { mag: 50, sign: false });
    data.append(i32 { mag: 173, sign: false });
    data.append(i32 { mag: 33, sign: false });
    data.append(i32 { mag: 4, sign: false });
    data.append(i32 { mag: 29, sign: false });
    data.append(i32 { mag: 243, sign: false });
    data.append(i32 { mag: 253, sign: false });
    data.append(i32 { mag: 186, sign: false });
    data.append(i32 { mag: 43, sign: false });
    data.append(i32 { mag: 241, sign: false });
    data.append(i32 { mag: 203, sign: false });
    data.append(i32 { mag: 254, sign: false });
    data.append(i32 { mag: 7, sign: false });
    data.append(i32 { mag: 214, sign: false });
    data.append(i32 { mag: 242, sign: false });
    data.append(i32 { mag: 36, sign: false });
    data.append(i32 { mag: 189, sign: false });
    data.append(i32 { mag: 52, sign: false });
    data.append(i32 { mag: 241, sign: false });
    data.append(i32 { mag: 221, sign: false });
    data.append(i32 { mag: 10, sign: false });
    data.append(i32 { mag: 249, sign: false });
    data.append(i32 { mag: 2, sign: false });
    data.append(i32 { mag: 218, sign: false });
    data.append(i32 { mag: 25, sign: false });
    data.append(i32 { mag: 230, sign: false });
    data.append(i32 { mag: 47, sign: false });
    data.append(i32 { mag: 11, sign: false });
    data.append(i32 { mag: 143, sign: false });
    data.append(i32 { mag: 4, sign: false });
    data.append(i32 { mag: 236, sign: false });
    data.append(i32 { mag: 60, sign: false });
    data.append(i32 { mag: 211, sign: false });
    data.append(i32 { mag: 237, sign: false });
    data.append(i32 { mag: 226, sign: false });
    data.append(i32 { mag: 33, sign: false });
    data.append(i32 { mag: 255, sign: false });
    data.append(i32 { mag: 252, sign: false });
    data.append(i32 { mag: 6, sign: false });
    data.append(i32 { mag: 17, sign: false });
    data.append(i32 { mag: 235, sign: false });
let extra = ExtraParams { fixed_point: Option::Some(FixedImpl::FP16x16(())) }; 
    TensorTrait::new(shape.span(), data.span(), Option::Some(extra))
}
