use array::ArrayTrait;
use orion::operators::tensor::core::{TensorTrait, Tensor, ExtraParams};
use orion::operators::tensor::implementations::impl_tensor_i32::Tensor_i32;
use orion::numbers::fixed_point::core::FixedImpl;
use orion::numbers::signed_integer::i32::i32;

fn sequential_quant_dense_BiasAdd_ReadVariableOp() -> Tensor<i32> {
    let mut shape = ArrayTrait::<usize>::new();
    shape.append(40);
    let mut data = ArrayTrait::<i32>::new();
    data.append(i32 { mag: 216, sign: false });
    data.append(i32 { mag: 255, sign: false });
    data.append(i32 { mag: 255, sign: false });
    data.append(i32 { mag: 255, sign: false });
    data.append(i32 { mag: 16, sign: false });
    data.append(i32 { mag: 12, sign: false });
    data.append(i32 { mag: 0, sign: false });
    data.append(i32 { mag: 0, sign: false });
    data.append(i32 { mag: 107, sign: false });
    data.append(i32 { mag: 21, sign: false });
    data.append(i32 { mag: 0, sign: false });
    data.append(i32 { mag: 0, sign: false });
    data.append(i32 { mag: 195, sign: false });
    data.append(i32 { mag: 215, sign: false });
    data.append(i32 { mag: 255, sign: false });
    data.append(i32 { mag: 255, sign: false });
    data.append(i32 { mag: 128, sign: false });
    data.append(i32 { mag: 17, sign: false });
    data.append(i32 { mag: 0, sign: false });
    data.append(i32 { mag: 0, sign: false });
    data.append(i32 { mag: 32, sign: false });
    data.append(i32 { mag: 10, sign: false });
    data.append(i32 { mag: 0, sign: false });
    data.append(i32 { mag: 0, sign: false });
    data.append(i32 { mag: 6, sign: false });
    data.append(i32 { mag: 31, sign: false });
    data.append(i32 { mag: 0, sign: false });
    data.append(i32 { mag: 0, sign: false });
    data.append(i32 { mag: 43, sign: false });
    data.append(i32 { mag: 8, sign: false });
    data.append(i32 { mag: 0, sign: false });
    data.append(i32 { mag: 0, sign: false });
    data.append(i32 { mag: 220, sign: false });
    data.append(i32 { mag: 20, sign: false });
    data.append(i32 { mag: 0, sign: false });
    data.append(i32 { mag: 0, sign: false });
    data.append(i32 { mag: 48, sign: false });
    data.append(i32 { mag: 6, sign: false });
    data.append(i32 { mag: 0, sign: false });
    data.append(i32 { mag: 0, sign: false });
let extra = ExtraParams { fixed_point: Option::Some(FixedImpl::FP16x16(())) }; 
    TensorTrait::new(shape.span(), data.span(), Option::Some(extra))
}
